{% extends "../templates/layout.twig" %}

{% block page__main %}
{% include "../php/machine-connect.php" %}

<section class="add-form page__centerer">
  <h1 class="add-form__title">Добавление нового заказа</h1>
  <form class="simple-form" action="../../php/create_client_order.php" method="post">
    <ul class="simple-form__list reset-list">
      <li class="simple-form__item simple-form__item--wide">
        <label class="simple-form__label" for="customer">Выберите заказчика*</label>
        <select name="customer" id="customer">
          <option value="Выберите заказчика" disabled>Выберите заказчика</option>
          <?php $query = mysqli_query($DB_connect, 'SELECT customer FROM `client` ORDER BY customer');
      while ($row = mysqli_fetch_assoc($query)) {
      ?>
          <option value="<?=$row['customer']?>"> "
            <?=$row['customer'] ?>"
          </option>
          <? } ?>
        </select>
      </li>
      <li class="simple-form__item simple-form__item--wide">
        <label class="simple-form__label" for="order"> Наименование заказа*</label>
        <textarea class="simple-form__input simple-form__textarea" id="order" name="order_title"
          placeholder="Наименование без кавычек, например Пельмени с мясом и картошкой" required></textarea>
      </li>
    </ul>
    <span class="simple-form__span">
        <sup>* - обязательные поля</sup>
      </span>
    <div class="simple-form__submit">
      <button class="simple-form__button" type="submit">Добавить новый заказ </button>
    </div>
  </form>
</section>

<script src="../js/send-to-php.min.js"></script>

{% endblock %}
