{% extends "../templates/layout.twig" %}

{% block page__main %}

<?php
$db_machine = 'lemo';
 ?>

 {% include "../php/machine-connect.php" %}

<form method="post" action="../php/create_report.php" autocomplete="off">
  <fieldset>
    <legend>Выберите диапазон для составления отчета</legend>
    <label for="date-from">С </label>
    <input type="date" name="date-from" required>
    <label for="date-to">По </label>
    <input type="date" name="date-to" required>
  </fieldset>
  <!-- <fieldset>
    <legend>Выберите необходимое оборудование</legend>
    <label for="mf1">Miraflex1</label>
    <input type="checkbox" name="mf1" id="mf1">
    <label for="mf2">Miraflex2</label>
    <input type="checkbox" name="mf2" id="mf2">
    <label for="lemo">LEMO</label>
    <input type="checkbox" name="lemo" id="lemo">
    <label for="fk4">Fisher4</label>
    <input type="checkbox" name="fk4" id="fk4">
    <label for="fk5">Fisher5</label>
    <input type="checkbox" name="fk5" id="fk5">
    <label for="fk6">Fisher6</label>
    <input type="checkbox" name="fk6" id="fk6">
    <label for="lm1">Laminator1</label>
    <input type="checkbox" name="lm1" id="lm1">
    <label for="lm2">Laminator2</label>
    <input type="checkbox" name="lm2" id="lm2">
    <label for="lm3">Laminator 3</label>
    <input type="checkbox" name="lm3" id="lm13">
  </fieldset> -->
  <button type="submit">Сформировать отчет</button>
  <button type="reset">Сбросить значения</button>
</form>

<!-- <table class="table-sort">
  <caption>Отчет простоя c -- по -- </caption>

  <thead class="table-sort__head">
    <tr class="table-sort__row">
      <th class="table-sort__header"></th>
      <th class="table-sort__header table-sort__header--sorted">Электро-механика</th>
      <th class="table-sort__header table-sort__header--sorted">Техническое обслуживание</th>
      <th class="table-sort__header table-sort__header--sorted">Персонал</th>
      <th class="table-sort__header table-sort__header--sorted">Заказы</th>
      <th class="table-sort__header table-sort__header--sorted">Сырье</th>
      <th class="table-sort__header table-sort__header--sorted">ИТОГО</th>
    </tr>
  </thead>
  <tbody class="table-sort__body">
    <tr class="table-sort__row">
      <th class="table-sort__header">{{ machines[2].name }}</th>
      <td>
        <?php
      $result = mysqli_query($DB_connect_machine, 'SELECT SUM(electro_mechanical) sum FROM primbase');
      $result = mysqli_fetch_assoc($result);
      $sum1=$result['sum'];
      echo $sum1. ' ч.';
        ?>
      </td>
      <td>
      </td>
      <td>
      <?php
      $result = mysqli_query($DB_connect_machine, 'SELECT SUM(no_human) sum FROM primbase');
      $result = mysqli_fetch_assoc($result);
      $sum2=$result['sum'];
      echo $sum2. ' ч.';
        ?>
      </td>
      <td>
      <?php
      $result = mysqli_query($DB_connect_machine, 'SELECT SUM(no_work) sum FROM primbase');
      $result = mysqli_fetch_assoc($result);
      $sum3=$result['sum'];
      echo $sum3. ' ч.';
        ?>
      </td>
      <td>
      <?php
      $result = mysqli_query($DB_connect_machine, 'SELECT SUM(no_raw) sum FROM primbase');
      $result = mysqli_fetch_assoc($result);
      $sum4=$result['sum'];
      echo $sum4. ' ч.';
        ?>
      </td>
      <td>
        <?php
      echo $sum1 + $sum2 + $sum3 + $sum4 . ' ч.';
      ?>
      </td>
    </tr>
    <tr class="table-sort__row">
      <th class="table-sort__header">{{ machines[2].name }}</th>
      <td>
        <?php
      $result = mysqli_query($DB_connect_machine, 'SELECT SUM(electro_mechanical) sum FROM primbase');
      $result = mysqli_fetch_assoc($result);
      $sum1=$result['sum'];
      echo $sum1. ' ч.';
        ?>
      </td>
      <td>
      </td>
      <td>
      <?php
      $result = mysqli_query($DB_connect_machine, 'SELECT SUM(no_human) sum FROM primbase');
      $result = mysqli_fetch_assoc($result);
      $sum2=$result['sum'];
      echo $sum2. ' ч.';
        ?>
      </td>
      <td>
      <?php
      $result = mysqli_query($DB_connect_machine, 'SELECT SUM(no_work) sum FROM primbase');
      $result = mysqli_fetch_assoc($result);
      $sum3=$result['sum'];
      echo $sum3. ' ч.';
        ?>
      </td>
      <td>
      <?php
      $result = mysqli_query($DB_connect_machine, 'SELECT SUM(no_raw) sum FROM primbase');
      $result = mysqli_fetch_assoc($result);
      $sum4=$result['sum'];
      echo $sum4. ' ч.';
        ?>
      </td>
      <td>
        <?php
      echo $sum1 + $sum2 + $sum3 + $sum4 . ' ч.';
      ?>
      </td>
    </tr>
  </tbody>

</table> -->
{% endblock %}
