{% extends "../templates/layout.twig" %}

{% block page__main %}

<?php

require_once './php/machine-connect.php';
require_once './php/db.php';


$machineType = $_GET['type'];
$machine = $_GET['machine'];
$taskId = $_GET['id'];

$conn = new mysqli($servername, $username, $password, $machine);
$task = getTask($conn, $taskId);

?>

<article>

  <form class="form form-block__form page__centerer" action="/php/task-update.php" method="POST">
    <h1 class="visually-hidden">Основная таблица ввода работ</h1>

    <fieldset class="form-block form-block--work">
      <legend class="form-block__title">График работ</legend>
      <ul class="form-block__list form-block__list--first">
        <li class="visually-hidden">
          <label class="form-block__label" for="machineType">Тип машины</label>
          <ul class="form-block__sublist">
            <li class="form-block__subitem">
              <input class="form-block__input" type="text" name="machineType" id="machineType" value="<?= $machineType ?>">
              <input class="form-block__input" type="text" name="db_machine" id="db_machine" value="<?= $machine ?>">
              <input class="form-block__input" type="text" name="task_id" id="task_id" value="<?= $taskId ?>">
              <input class="form-block__input" type="text" name="search_url" id="search_url" value="<?= $_SERVER['HTTP_REFERER'] ?>">
            </li>
          </ul>
        </li>
        <li class="form-block__item">
          <label class="form-block__label" for="work_date">Рабочая смены</label>
          <ul class="form-block__sublist">
            <li class="form-block__subitem">
              <input class="form-block__input" type="date" name="work_date" id="work_date"
                     value="<?= $task['work_date'] ?>" required>
            </li>
          </ul>
        </li>

        <li class="form-block__item">
          <label class="form-block__label" for="work_shift">Рабочая смена</label>
          <ul class="form-block__sublist form-block__sublist--radio">
            <li class="form-block__subitem">
              <input class="form-block__input form-block__input--radio" id="work_shift-1" type="radio" name="work_shift" value="1" required
                <?= $task['work_shift'] == 1 ? 'checked' : '' ?>>
              <label class="form-block__sublabel" for="work_shift-1">с 8 до 20</label>
            </li>
            <li class="form-block__subitem">
              <input class="form-block__input form-block__input--radio" id="work_shift-2" type="radio" name="work_shift" value="2" required
                <?= $task['work_shift'] == 2 ? 'checked' : '' ?>>
              <label class="form-block__sublabel" for="work_shift-2">с 20 до 8</label>
            </li>
          </ul>
        </li>

        <li class="form-block__item">
          <label class="form-block__label" for="master">Мастер смены</label>
          <ul class="form-block__sublist">
            <li class="form-block__subitem">
              <input class="form-block__input" name="master" type="text" id="master" list="masters" value="<?= $task['master'] ?>" required>
              <datalist id="masters">
                <?php $query = mysqli_query($DB_connect, "SELECT login FROM `master` ORDER BY login");
                while ($row = mysqli_fetch_assoc($query)) {
                ?>
                <option value=<?= $row['login'] ?>>
                  <? } ?>
              </datalist>
            </li>
            </li>
          </ul>
        </li>

        <?php if ($machineType == "print"): ?>

          <li class="form-block__item">
            <label class="form-block__label" for="operator1">Оператор 1</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" name="operator1" type="text" id="operator1" list="operators" value="<?= $task['operator1'] ?>"
                       required>
                <datalist id="operators">
                  <?php $query = mysqli_query($DB_connect, "SELECT login FROM `operator` ORDER BY login");
                  while ($row = mysqli_fetch_assoc($query)) {
                  ?>
                  <option value=<?= $row['login'] ?>>
                    <? } ?>
                </datalist>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="operator2">Оператор 2</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" name="operator2" type="text" id="operator2" list="operators" value="<?= $task['operator2'] ?>"
                       required>
                <datalist id="operators">
                  <?php $query = mysqli_query($DB_connect, "SELECT login FROM `operator` ORDER BY login");
                  while ($row = mysqli_fetch_assoc($query)) {
                  ?>
                  <option value=<?= $row['login'] ?>>
                    <? } ?>
                </datalist>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="operator3">Оператор 3</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" name="operator3" type="text" id="operator3" list="operators" value="<?= $task['operator3'] ?>"
                       required>
                <datalist id="operators">
                  <?php $query = mysqli_query($DB_connect, "SELECT login FROM `operator` ORDER BY login");
                  while ($row = mysqli_fetch_assoc($query)) {
                  ?>
                  <option value=<?= $row['login'] ?>>
                    <? } ?>
                </datalist>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="operator_helper">Помощник оператора</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" name="operator_helper" type="text" id="operator_helper" list="operators"
                       value="<?= $task['operator_helper'] ?>" required>
                <datalist id="operators">
                  <?php $query = mysqli_query($DB_connect, "SELECT login FROM `operator` ORDER BY login");
                  while ($row = mysqli_fetch_assoc($query)) {
                  ?>
                  <option value=<?= $row['login'] ?>>
                    <? } ?>
                </datalist>
              </li>
            </ul>
          </li>

        <?php endif; ?>
        <?php if ($machineType == "lamination"): ?>

          <li class="form-block__item">
            <label class="form-block__label" for="operator">Оператор</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" name="operator" type="text" id="operator" list="operators" value="<?= $task['operator'] ?>" required>
                <datalist id="operators">
                  <?php $query = mysqli_query($DB_connect, "SELECT login FROM `operator` ORDER BY login");
                  while ($row = mysqli_fetch_assoc($query)) {
                  ?>
                  <option value=<?= $row['login'] ?>>
                    <? } ?>
                </datalist>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="operator_student">Ученик оператора</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" name="operator_student" type="text" id="operator_student" list="operators"
                       value="<?= $task['operator_student'] ?>" required>
                <datalist id="operators">
                  <?php $query = mysqli_query($DB_connect, "SELECT login FROM `operator` ORDER BY login");
                  while ($row = mysqli_fetch_assoc($query)) {
                  ?>
                  <option value=<?= $row['login'] ?>>
                    <? } ?>
                </datalist>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="operator_helper">Подсобный рабочий</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" name="operator_helper" type="text" id="operator_helper" list="operators"
                       value="<?= $task['operator_helper'] ?>" required>
                <datalist id="operators">
                  <?php $query = mysqli_query($DB_connect, "SELECT login FROM `operator` ORDER BY login");
                  while ($row = mysqli_fetch_assoc($query)) {
                  ?>
                  <option value=<?= $row['login'] ?>>
                    <? } ?>
                </datalist>
              </li>
            </ul>
          </li>

        <?php endif; ?>

        <li class="form-block__item">
          <label class="form-block__label" for="customer">Заказчик</label>
          <ul class="form-block__sublist">
            <li class="form-block__subitem">
              <input class="form-block__input" name="customer" type="text" id="customer" list="customers" value="<?= $task['customer'] ?>" required>
              <datalist id="customers">
                <?php $query = mysqli_query($DB_connect, "SELECT customer FROM `client` ORDER BY customer");
                while ($row = mysqli_fetch_assoc($query)) {
                ?>
                <option value="<?= $row['customer'] ?>">
                  <? } ?>
              </datalist>
            </li>
          </ul>
        </li>

        <li class="form-block__item">
          <label class="form-block__label" for="print_title">Наименование заказа</label>
          <ul class="form-block__sublist">
            <li class="form-block__subitem">
              <input class="form-block__input" name="print_title" type="text" id="print_title" list="titles" value="<?= $task['print_title'] ?>"
                     required>
              <datalist id="titles">
                <?php $query = mysqli_query($DB_connect, "SELECT order_title FROM `client_order` ORDER BY order_title  ");
                while ($row = mysqli_fetch_assoc($query)) {
                ?>
                <option value="<?= $row['order_title'] ?>">
                  <? } ?>
              </datalist>
            </li>
          </ul>
        </li>

        <li class="form-block__item">
          <label class="form-block__label" for="tkn">Номер ТКН</label>
          <ul class="form-block__sublist">
            <li class="form-block__subitem">
              <input class="form-block__input" type="text" name="tkn" id="tkn"
                     value="<?= $task['tkn'] ?>" pattern="[0-9а-я]+" required>
            </li>
          </ul>
        </li>

        <li class="form-block__item">
          <label class="form-block__label" for="circulation">Тираж <small>(план выработки)</small></label>
          <ul class="form-block__sublist">
            <li class="form-block__subitem">
              <input class="form-block__input" type="number" name="circulation" id="circulation"
                     value="<?= $task['circulation'] ?>" title="кг" min="0" required>
            </li>
          </ul>
        </li>

        <li class="form-block__item">
          <label class="form-block__label" for="work_plan">Планируемое время</label>
          <ul class="form-block__sublist">
            <li class="form-block__subitem">
              <input class="form-block__input" type="number" name="work_plan" id="work_plan"
                     value="<?= $task['work_plan'] ?>" title="часов" maxlength="3" min="0" required>
            </li>
          </ul>
        </li>

        <li class="form-block__item">
          <label class="form-block__label" for="work_start">Начало работ</label>
          <ul class="form-block__sublist">
            <li class="form-block__subitem">
              <input class="form-block__input" type="datetime-local" name="work_start" id="work_start"
                     value="<?= $task['work_start'] ?>" required>
            </li>
          </ul>
        </li>

        <li class="form-block__item">
          <label class="form-block__label" for="work_finish">Окончание работ</label>
          <ul class="form-block__sublist">
            <li class="form-block__subitem">
              <input class="form-block__input" type="datetime-local" name="work_finish" id="work_finish"
                     value="<?= $task['work_finish'] ?>" required>
            </li>
          </ul>
        </li>


        <li class="form-block__item">
          <label class="form-block__label" for="work_fact">Фактическое время</label>
          <ul class="form-block__sublist">
            <li class="form-block__subitem">
              <input class="form-block__input" type="number" name="work_fact" id="work_fact"
                     value="<?= $task['work_fact'] ?>" title="часов">
            </li>
          </ul>
        </li>
      </ul>
    </fieldset>

    <fieldset class="form-block form-block--material">
      <legend class="form-block__title">Расход материала</legend>
      <ul class="form-block__list form-block__second">
        <div class="form-block__wrapper">
          <li class="form-block__item">
            <p class="form-block__description">Материал 1</p>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <label class="visually-hidden" for="material-1">Материал</label>
                <select class="form-block__input" name="material1" id="material-1" required>
                  <option value="Выберите первый материал" disabled>Выберите первый материал</option>
                  <?php $query = mysqli_query($DB_connect, "SELECT material FROM `matbase` ORDER BY material");
                  while ($row = mysqli_fetch_assoc($query)) {
                    ?>
                    <option value=<?= $row['material'] ?> <?= $row['material'] == $task['material1'] ? 'selected' : '' ?>>
                      <?= $row['material'] ?>
                    </option>
                  <? } ?>
                </select>
              </li>
              </li>
              <li class="form-block__subitem">
                <label class="visually-hidden" for="matcount-1-plan">Количество сырья плановое</label>
                <input class="form-block__input" type="number" name="mat1count_plan" id="matcount-1-plan"
                       value="<?= $task['mat1count_plan'] ?>" title="Количество сырья плановое, кг" step="0.01" required>
              </li>
              <li class="form-block__subitem">
                <label class="visually-hidden" for="matcount-1">Количество сырья</label>
                <input class="form-block__input" type="number" name="mat1count" id="matcount-1"
                       value="<?= $task['mat1count'] ?>" title="Количество сырья фактическое, кг" step="0.01" required>
              </li>
              <li class="form-block__subitem">
                <label class="visually-hidden" for="width1">Ширина</label>
                <input class="form-block__input" type="number" name="width1" id="width1"
                       value="<?= $task['width1'] ?>" title="Ширина, мм" step="0.01" required>
              </li>
              <li class="form-block__subitem">
                <label class="visually-hidden" for="thickness1">Толщина</label>
                <input class="form-block__input" type="number" name="thickness1" id="thickness1"
                       value="<?= $task['thickness1'] ?>" title="Толщина, мкм" step="0.01" required>
              </li>
            </ul>
          </li>
          </li>

          <?php if ($machineType == "lamination"): ?>
            <li class="form-block__item">
              <p class="form-block__description">Материал 2</p>
              <ul class="form-block__sublist">
                <li class="form-block__subitem">
                  <label class="visually-hidden" for="material-2">Материал</label>
                  <select class="form-block__input" name="material2" id="material-2">
                    <option value="Выберите первый материал" disabled>Выберите второй материал</option>
                    <?php $query = mysqli_query($DB_connect, "SELECT material FROM `matbase` ORDER BY material");
                    while ($row = mysqli_fetch_assoc($query)) {
                      ?>
                      <option value=<?= $row['material'] ?> <?= $row['material'] == $task['material1'] ? 'selected' : '' ?>>
                        <?= $row['material'] ?>
                      </option>
                    <? } ?>
                  </select>
                </li>
                </li>
                <li class="form-block__subitem">
                  <label class="visually-hidden" for="matcount-2-plan">Количество сырья плановое</label>
                  <input class="form-block__input" type="number" name="mat2count_plan" id="matcount-2-plan"
                         value="<?= $task['mat2count_plan'] ?>" title="планируемое количество, кг" step="0.01" required>
                </li>
                <li class="form-block__subitem">
                  <label class="visually-hidden" for="matcount-2">Количество сырья</label>
                  <input class="form-block__input" type="number" name="mat2count" id="matcount-2"
                         value="<?= $task['mat2count'] ?>" title="фактическое количество, кг" step="0.01" required>
                </li>
                <li class="form-block__subitem">
                  <label class="visually-hidden" for="width2">Ширина</label>
                  <input class="form-block__input" type="number" name="width2" id="width2"
                         value="<?= $task['width2'] ?>" title="ширина, мм" step="0.01" required>
                </li>
                <li class="form-block__subitem">
                  <label class="visually-hidden" for="thickness2">Толщина</label>
                  <input class="form-block__input" type="number" name="thickness2" id="thickness2"
                         value="<?= $task['thickness2'] ?>" title="толщина, мкм" step="0.01" required>
                </li>
              </ul>
            </li>
            </li>
            <li class="form-block__item">
              <p class="form-block__description">Материал 3</p>
              <ul class="form-block__sublist">
                <li class="form-block__subitem">
                  <label class="visually-hidden" for="material-3">Материал</label>
                  <select class="form-block__input" name="material3" id="material-3">
                    <option value="Выберите первый материал" disabled>Выберите дуплекс-материал</option>
                    <?php $query = mysqli_query($DB_connect, "SELECT material FROM `matbase` ORDER BY material");
                    while ($row = mysqli_fetch_assoc($query)) {
                      ?>
                      <option value=<?= $row['material'] ?> <?= $row['material'] == $task['material1'] ? 'selected' : '' ?>>
                        <?= $row['material'] ?>
                      </option>
                    <? } ?>
                  </select>
                </li>
                </li>
                <li class="form-block__subitem">
                  <label class="visually-hidden" for="matcount-3-plan">Количество сырья плановое</label>
                  <input class="form-block__input" type="number" name="mat3count_plan" id="matcount-3-plan"
                         value="<?= $task['mat3count_plan'] ?>" title="планируемое количество, кг" step="0.01" required>
                </li>
                <li class="form-block__subitem">
                  <label class="visually-hidden" for="matcount-3">Количество сырья</label>
                  <input class="form-block__input" type="number" name="mat3count" id="matcount-3"
                         value="<?= $task['mat3count'] ?>" title="фактическое количество, кг" step="0.01" required>
                </li>
                <li class="form-block__subitem">
                  <label class="visually-hidden" for="width3">Ширина</label>
                  <input class="form-block__input" type="number" name="width3" id="width3"
                         value="<?= $task['width3'] ?>" title="ширина, мм" step="0.01" required>
                </li>
                <li class="form-block__subitem">
                  <label class="visually-hidden" for="thickness3">Толщина</label>
                  <input class="form-block__input" type="number" name="thickness3" id="thickness3"
                         value="<?= $task['thickness3'] ?>" title="толщина, мкм" step="0.01" required>
                </li>
              </ul>
            </li>
            </li>
          <?php endif; ?>

        </div>
        <div class="form-block__wrapper">
          <li class="form-block__item">
            <label class="form-block__label" for="workout">Выработка</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="workout_mass" id="workout"
                       value="<?= $task['workout_mass'] ?>" title="кг" step="0.01" required>
              </li>
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="workout_length" id="workout"
                       value="<?= $task['workout_length'] ?>" title="погонные метры" step="0.01" required>
              </li>
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="workout_m2" id="workout"
                       value="<?= $task['workout_m2'] ?>" title="квадратные метры" step="0.01">
              </li>
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="otk_mass" id="workout"
                       value="<?= $task['otk_mass'] ?>" title="выработка на ОТК" step="0.01" required>
              </li>
            </ul>
          </li>
        </div>
        <div class="form-block__wrapper">
          <li class="form-block__item">
            <label class="form-block__label" for="waste">Отходы</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="waste_plan" id="waste"
                       value="<?= $task['waste_plan'] ?>" title="план, кг" step="0.01" required>
              </li>
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="waste_print" id="waste"
                       value="<?= $task['waste_print'] ?>" title="печати, кг" step="0.01" required>
              </li>

              <?php if ($machineType == "print"): ?>
                <li class="form-block__subitem">
                  <input class="form-block__input" type="number" name="waste_raw" id="waste"
                         value="<?= $task['waste_raw'] ?>" title="сырья , кг" step="0.01" required>
                </li>
              <?php endif; ?>

              <?php if ($machineType == "lamination"): ?>
                <li class="form-block__subitem">
                  <input class="form-block__input" type="number" name="waste_lam" id="waste"
                         value="<?= $task['waste_lam'] ?>"  title="ламинации , кг" step="0.01" required>
                </li>
              <?php endif; ?>

              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="waste_sum" id="waste"
                       value="<?= $task['waste_sum'] ?>" title="итоговые , кг" step="0.01">
              </li>
            </ul>
          </li>
        </div>

        <?php if ($machineType == "print"): ?>
          <li class="form-block__item">
            <label class="form-block__label" for="colors">Количество красок</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="colors" id="colors"
                       value="<?= $task['colors'] ?>" title="от 0 до 10" min="0" max="10" required>
              </li>
            </ul>
          </li>
        <?php endif; ?>
      </ul>
    </fieldset>

    <fieldset class="form-block form-block--techopp">
      <legend class="form-block__title">Технические операции</legend>
      <ul class="form-block__list form-block__list--third">

        <li class="form-block__item">
          <label class="form-block__label" for="electro_mechanical">Эл/мех часть</label>
          <ul class="form-block__sublist">
            <li class="form-block__subitem">
              <input class="form-block__input" type="number" name="electro" id="electro_mechanical"
                     value="<?= $task['electro'] ?>" step="0.01" title="электрика, часов" required>
            </li>
            <li class="form-block__subitem">
              <input class="form-block__input" type="number" name="mechanical" id="electro_mechanical"
                     value="<?= $task['mechanical'] ?>" step="0.01" title="механика, часов" required>
            </li>
          </ul>
        </li>

        <?php if ($machineType == "print"): ?>
          <li class="form-block__item">
            <label class="form-block__label" for="aniloks">Подбор анилоксов</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="aniloks" id="aniloks"
                       value="<?= $task['aniloks'] ?>" step="0.01" title="часов" required>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="clean_machine">Мытье машины</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="clean_machine" id="clean_machine"
                       value="<?= $task['clean_machine'] ?>" step="0.01" title="часов" required>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="form_glue">Переклейка форм</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="form_glue" id="form_glue"
                       value="<?= $task['form_glue'] ?>" step="0.01" title="часов" required>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="rakel">Замена ракеля</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="rakel" id="rakel"
                       value="<?= $task['rakel'] ?>" step="0.01" title="часов" required>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="clean_dry">Чистка сушки</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="clean_dry" id="clean_dry"
                       value="<?= $task['clean_dry'] ?>" step="0.01" title="часов" required>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="clean_val">Чистка валов</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="clean_val" id="clean_val"
                       value="<?= $task['clean_val'] ?>" step="0.01" title="часов" required>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="prepare">Приправка</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="prepare_mass" id="prepare"
                       value="<?= $task['prepare_mass'] ?>" title="кг" step="0.01" required>
              </li>
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="prepare_hours" id="prepare"
                       value="<?= $task['prepare_hours'] ?>" title="часов" step="0.01" required>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="color_correction">Коррекция красок</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="correction_PN" id="color_correction"
                       value="<?= $task['correction_PN'] ?>" title="PN" step="0.01" required>
              </li>
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="correction_CMYK" id="color_correction"
                       value="<?= $task['correction_CMYK'] ?>" title="CMYK" step="0.01" required>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="speed">Скорость печати</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="speed" id="speed"
                       value="<?= $task['speed'] ?>" step="0.01" title="м/мин" required>
              </li>
            </ul>
          </li>
        <?php endif; ?>

        <?php if ($machineType == "lamination"): ?>
          <li class="form-block__item">
            <label class="form-block__label" for="prepare">Приправка</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="prepare" id="prepare"
                       value="<?= $task['prepare'] ?>"  step="0.01" title="часов" required>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="prepare_shirt">Приправка с заменой рубашки</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="prepare_shirt" id="prepare_shirt"
                       value="<?= $task['prepare_shirt'] ?>"  step="0.01" title="часов" required>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="flushing">Расход на промывку</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="flushing" id="flushing"
                       value="<?= $task['flushing'] ?>"  step="0.01" title="часов" required>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="tech_clean">Техчистка</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="tech_clean" id="tech_clean"
                       value="<?= $task['tech_clean'] ?>" step="0.01" title="часов" required>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="change_glue">Замена клея</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="change_glue" id="change_glue"
                       value="<?= $task['change_glue'] ?>" step="0.01" title="часов" required>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="calibrating">Калибровка</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="calibrating" id="calibrating"
                       value="<?= $task['calibrating'] ?>" step="0.01" title="часов" required>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="tech_service">Техническое обслуживание</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="tech_service" id="tech_service"
                       value="<?= $task['tech_service'] ?>"  step="0.01" title="часов" required>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="remain">Остаток</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="remain_perv" id="remain"
                       value="<?= $task['remain_perv'] ?>" title="первички" step="0.01" required>
              </li>
              <li class="form-block__subitem">
                <input class="form-block__input" type="number" name="remain_sec" id="remain"
                       value="<?= $task['remain_sec'] ?>" title="вторички" step="0.01" required>
              </li>
            </ul>
          </li>

          <li class="form-block__item">
            <label class="form-block__label" for="prepare_ok">Приправка принята</label>
            <ul class="form-block__sublist">
              <li class="form-block__subitem">
                <input class="form-block__input form-block__input--radio" id="prepare-radio-1"
                       type="radio" name="prepare_ok" value="Да" <?= $task['prepare_ok'] == 'Да' ? 'checked' : '' ?>  required>
                <label class="form-block__input" for="prepare-radio-1">Да</label>
              </li>
              <li class="form-block__subitem">
                <input class="form-block__input form-block__input--radio" id="prepare-radio-2"
                       type="radio" name="prepare_ok" value="Нет" <?= $task['prepare_ok'] == 'Нет' ? 'checked' : '' ?> required>
                <label class="form-block__input" for="prepare-radio-2">Нет</label>
              </li>
            </ul>
          </li>
        <?php endif; ?>

        <li class="form-block__item">
          <label class="form-block__label" for="no_">Часы отсутствия</label>
          <ul class="form-block__sublist">
            <li class="form-block__subitem">
              <input class="form-block__input" type="number" name="no_human" id="no_"
                     value="<?= $task['no_human'] ?>" title="людей" step="0.01" required>
            </li>
            <li class="form-block__subitem">
              <input class="form-block__input" type="number" name="no_work" id="no_"
                     value="<?= $task['no_work'] ?>" title="заказов" step="0.01" required>
            </li>
            <li class="form-block__subitem">
              <input class="form-block__input" type="number" name="no_raw" id="no_"
                     value="<?= $task['no_raw'] ?>" title="сырья" step="0.01" required>
            </li>
          </ul>
        </li>

        <li class="form-block__item">
          <label class="form-block__label" for="diff_circulation">Разница тиража</label>
          <ul class="form-block__sublist">
            <li class="form-block__subitem">
              <input class="form-block__input" type="number" name="diff_circulation" id="diff_circulation"
                     value="<?= $task['diff_circulation'] ?>" title="кг">
            </li>
          </ul>
        </li>

        <li class="form-block__item form-block__item--textarea">
          <label class="form-block__label" for="notes">Примечание</label>
          <ul class="form-block__sublist">
            <li class="form-block__subitem">
              <textarea class="form-block__input form-block__input--textarea" name="notes" id="notes"><?= $task['notes'] ?></textarea>
            </li>
          </ul>
        </li>
      </ul>
    </fieldset>


    <div class="form-footer">
      <button class="form-footer__main-button" type="submit">Изменить задачу</button>
    </div>
  </form>
  <!--  <script src="./js/formCheck.min.js"></script>-->
  <!--  <script src="../js/send-to-php.min.js"></script>-->
</article>


{% endblock %}
