{% extends "../../templates/layout.twig" %}

{% block page__main %}

{% set machineId = 0 %}
{% set machineName = machines[machineId].name %}
{% set machineType = machines[machineId].type %}
{% set machineDB = machines[machineId].db %}

<?php
$db_machine = "miraflex1";
$machineType = "print";
require './php/machine-connect.php';
?>

{% include "../../templates/machine-input.twig" %}

{% endblock %}
